# List of options:
# "password"	=> ""	# The password

development:
  password: thisisaverylongpasswordtopreventbruteforceattacks

test:
  password: thisisaverylongpasswordtopreventbruteforceattacks

production:
  password: thisisaverylongpasswordtopreventbruteforceattacks
